apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-datash-org
spec:
  replicas: 2
  selector:
    matchLabels:
      app: www-datash-org
  template:
    metadata:
      labels:
        app: www-datash-org
    spec:
      containers:
        - name: quickweb
          image: ghcr.io/pypiplus/website:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 350m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: www-datash-org
spec:
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
  selector:
    app: www-datash-org
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: www-datash-org
spec:
  rules:
    - host: www.datash.org
      http:
        paths:
          - backend:
              serviceName: www-datash-org
              servicePort: 8080
