# https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images

name: Publish Docker image
on:
  push:
    branches: main

jobs:
  pulish-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/pypiplus/website:latest
