# https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images

name: Publish Docker image
on:
  push:
    branches: [ main ]

jobs:
  pulish-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/pypiplus/website:latest

      -
        name: Set kubernetes cluster context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
        id: setcontext

      -
        name: Deploy to K8s cluster
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
              k8s/deployment.yaml
          kubectl-version: 'latest'
